# Generated by Django 3.2 on 2026-04-15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0192_add_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='level number')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('accent_color', models.CharField(default='#8da2c7', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[A-Fa-f0-9]{3}){1,2}$', 'Invalid colour.')], verbose_name='accent colour')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('is_visible', models.BooleanField(default=True, verbose_name='publicly visible')),
                ('callout_title', models.CharField(blank=True, max_length=140, verbose_name='callout title')),
                ('callout_content', models.TextField(blank=True, verbose_name='callout content')),
            ],
            options={
                'verbose_name': 'roadmap level',
                'verbose_name_plural': 'roadmap levels',
                'ordering': ('order', 'level'),
            },
        ),
        migrations.CreateModel(
            name='RoadmapLevelContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('title_override', models.CharField(blank=True, max_length=180, verbose_name='title override')),
                ('summary', models.CharField(blank=True, max_length=220, verbose_name='summary')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_links', to='judge.contest', verbose_name='contest')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_contests', to='judge.roadmaplevel', verbose_name='level')),
            ],
            options={
                'verbose_name': 'roadmap contest',
                'verbose_name_plural': 'roadmap contests',
                'ordering': ('order', 'id'),
                'unique_together': {('level', 'contest')},
            },
        ),
    ]
